In [ ]:
#1.	Write a python method that adds 2 to the even numbers and 3 to the odd numbers in the list of values between 1 to 100?

In [ ]:
def main(x):
  for i in x:
    if i%2 ==0:
      i = i +2
      print(i)
    elif i%2 !=0:
      i = i +3
      print(i)

a = list(range(1,101))
main(a)





4
4
6
6
8
8
10
10
12
12
14
14
16
16
18
18
20
20
22
22
24
24
26
26
28
28
30
30
32
32
34
34
36
36
38
38
40
40
42
42
44
44
46
46
48
48
50
50
52
52
54
54
56
56
58
58
60
60
62
62
64
64
66
66
68
68
70
70
72
72
74
74
76
76
78
78
80
80
82
82
84
84
86
86
88
88
90
90
92
92
94
94
96
96
98
98
100
100
102
102


In [ ]:
#2.	Python program that calculates the mean of numbers in a list between 250 to 500?

In [ ]:
x = list(range(250,501))
total_sum = sum(x)
count = len(x)
mean = total_sum/count
print(mean)



375.0


In [ ]:
#3.	Python code to create ones and zeros of shape 5x10 using NumPy array? And1 a create two 1D arrays of shape 3xnd find dot product of it

In [ ]:
import numpy as np
x = np.random.choice([0,1],size =(5,10))
x

array([[1, 0, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 1, 1, 0, 1],
       [0, 1, 0, 0, 1, 1, 1, 0, 0, 1],
       [0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1]])

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
x.shape


(3,)

In [ ]:
x.ndim

1

In [ ]:
import numpy as np
np.dot(x,y)

32

In [ ]:
#4.	Write a program to find a minimum of three numbers in a list [453,567,212]

In [ ]:
l1 = [453,567,212]
minimum = min(l1)
print("min of x:", minimum)

min of x: 212


In [ ]:
#5.	Write a Python program that creates a 2D NumPy array called ‘arr’ with dimensions 3x4, filled with integers between 1 and 10 (inclusive). Calculate and print the mean value of the array.

In [ ]:
x = np.array([
    [1,2,3,4],
    [6,5,5,4],
    [6,2,3,8]])
x

array([[1, 2, 3, 4],
       [6, 5, 5, 4],
       [6, 2, 3, 8]])

In [ ]:
x.shape

(3, 4)

In [ ]:
x.ndim

2

In [ ]:
np.mean(x)

4.083333333333333

In [ ]:
#6.	Write a python program to find factorial of 5 : fact(5) = 5x4x3x2x1

In [ ]:
a = 1
for i in range(5,0,-1):
  a = a*i
print(a)


120


In [ ]:
#Write a python program to create a dictionary with keys as even and odd numbers between 1 to 10 and calculate sum of even and off numbers?

In [ ]:

x=list(range(1,11))
e_sum=0
o_sum=0
ndict={}
for i in x:
  if (i % 2 == 0):
      e_sum = e_sum + i
      ndict['even']=e_sum
  else:
      o_sum = o_sum+i
      ndict['odd']=o_sum
print(ndict)




{'odd': 25, 'even': 30}


In [ ]:
#8.	 Write a Python program to reverse a string

In [3]:
string = 'nishant'
a =''
for i in string:
  a =i+a
print(a)

tnahsin


In [ ]:
#9.	Write a Python program that takes a 2D NumPy array ‘arr’ as input and determine shape and dimension and add new axis.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
C = arr[:,np.newaxis]

In [ ]:
C

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
#10.	Write a python program to perform type conversion
a.	6.53 to int
b.	8 to float
c.	9.123 to string


In [ ]:
number_int = int(6.53)
print(number_int)

6


In [ ]:
x = float(8)
print(x)

8.0


In [ ]:
x = str(9.123)
print(x)

9.123
